apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: node-app
    spec: # pod spec
      containers:
      - name: node-server
        image: htdangkhoa/node-app
        ports:
        - containerPort: 3000