version: '3'

services:
  app:
    build: .
    container_name: app
    command: yarn start
    volumes:
      - .:/usr/src/app
    ports:
      - 9090:9090

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

volumes:
  node_modules: